print("-"*60)
print("welcome to addition program".center(60))
x=int(input("enter x:"))
y=int(input("enter y:"))
print(f"x={x}".center(60))
print(f"y={y}".center(60))
print(f"{x}+{y}={x+y}".center(60))
print("-"*60)
print("-"*60)
print("-"*60)
print("-"*60)
print("-"*60)
print("-"*60)
print("-"*60)
